export const unitParameter = {
    length: [
      {value: 'km', name: 'Kilometer (km)'},
      {value: 'm', name: 'Meter (m)'},
      {value: 'cm', name: 'Centimeter (cm)'},
      {value: 'mm', name: 'Millimeter (mm)'},
      {value: 'μm', name: 'Micrometer (μm)'},
      {value: 'nm', name: 'Nanometer (nm)'},
      {value: 'ft', name: 'Foot (ft)'},
      {value: 'mi', name: 'Mile (mi)'},
      {value: 'yd', name: 'yard (yd)'},
      {value: 'in', name: 'Inch (in)'},
    ],
    mass: [
      {value: 'kg', name: 'Kilogram (kg)'},
      {value: 'g', name: 'Gram (g)'},
      {value: 'mg', name: 'Milligram (mg)'},
      {value: 'μg', name: 'Microgram (μg)'},
      {value: 'lb', name: 'Pound (lb)'},
      {value: 'oz', name: 'Ounce (oz)'},
      {value: 't', name: 'Ton (t)'},
      {value: 'mt', name: 'Metric Ton (t)'},
    ],
    temperature: [
      {value: 'C', name: 'Celsius (C)'},
      {value: 'K', name: 'Kelvin (K)'},
      {value: 'F', name: 'Fahrenheit (F)'},
    ],
    area: [
      {value: 'km2', name: 'Square Kilometer (km2)'},
      {value: 'm2', name: 'Square Meter (m2)'},
      {value: 'cm2', name: 'Square Centimeter (cm2)'},
      {value: 'mm2', name: 'Square Millimeter (mm2)'},
      {value: 'μm2', name: 'Square Micrometer (μm2)'},
      {value: 'nm2', name: 'Square Nanometer (nm2)'},
      {value: 'ha', name: 'Hectare (ha)'},
      {value: 'mi2', name: 'Square Mile (mi2)'},
      {value: 'yd2', name: 'Square Yard (yd2)'},
      {value: 'ft2', name: 'Square Foot (ft2)'},
      {value: 'in2', name: 'Square Inch (in2)'},
      {value: 'ac', name: 'Acre (ac)'},
    ],
    volume: [
      {value: 'km3', name: 'Cubic Kilometer (C)'},
      {value: 'm3', name: 'Cubic Meter (C)'},
      {value: 'cm3', name: 'Cubic Centimeter (C)'},
      {value: 'mm3', name: 'Cubic Millimeter (C)'},
      {value: 'l', name: 'Liter (l)'},
      {value: 'ml', name: 'Milliliter (ml)'},
      {value: 'Ml', name: 'Megaliter (Ml)'},
      {value: 'Gl', name: 'US Gallon (Gl)'},
      {value: 'fl-oz', name: 'Fluid Ounce (fl-oz)'},
      {value: 'pnt', name: 'Pint (pnt)'},
      {value: 'ft3', name: 'Cubic Foot (ft3)'},
      {value: 'yd3', name: 'Cubic Yard (yd3)'},
      {value: 'in3', name: 'Cubic Inch (in3)'},
    ],
    time: [
      {value: 'h', name: 'Hours (h)'},
      {value: 'min', name: 'Minutes (m)'},
      {value: 's', name: 'Seconds (s)'},
      {value: 'ms', name: 'Milliseconds (ms)'},
      {value: 'μs', name: 'Microseconds (μs)'},
      {value: 'ns', name: 'Nanoseconds (ns)'},
      {value: 'd', name: 'Days (d)'},
      {value: 'week', name: 'Weeks (week)'},
      {value: 'month', name: 'Months (month)'},
      {value: 'year', name: 'Years (year)'},
    ],
  }